version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teachdrop-app
    restart: always
    environment:
      APP_ENV: production
      # other env vars
    volumes:
      - .:/var/www
    networks:
      - teachdrop-network
    ports:
      - "9000:9000"  # Expose PHP-FPM or Laravel dev server port if needed

  db:
    image: mysql:8
    container_name: teachdrop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teachdropDB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - teachdrop-network

volumes:
  db-data:

networks:
  teachdrop-network:
